/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test1;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.tree.TreePath;

/**
 *
 * @author nsags
 */
public class AgentSida extends javax.swing.JFrame {

    String namn;
    private String typ;
    private String fonster;

    /**
     * Creates new form agentSida
     */
    public AgentSida() {

        initComponents();
        namn = ForstaSida.aNamn();
        lblValkommen.setText("Välkommen " + namn);
        listaAllUtrustning();
        toppListaSvealand();
        toppListaGotaland();
        toppListaNorrland();
        for (int i = 0; i < jTree1.getRowCount(); i++) {
            jTree1.expandRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValkommen = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();
        btnNylosen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfUtrustning = new javax.swing.JTextArea();
        txtTopp3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        txtTopp1 = new javax.swing.JTextArea();
        txtTopp2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValkommen.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        lblValkommen.setText("jLabel1");

        btnLoggaUt.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        btnNylosen.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnNylosen.setText("Byt lösenord");
        btnNylosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNylosenActionPerformed(evt);
            }
        });

        txtfUtrustning.setEditable(false);
        txtfUtrustning.setColumns(1);
        txtfUtrustning.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        txtfUtrustning.setRows(5);
        txtfUtrustning.setToolTipText("");
        jScrollPane1.setViewportView(txtfUtrustning);

        txtTopp3.setEditable(false);
        txtTopp3.setColumns(2);
        txtTopp3.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        txtTopp3.setRows(3);
        txtTopp3.setTabSize(4);
        txtTopp3.setToolTipText("");
        txtTopp3.setAutoscrolls(false);
        txtTopp3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel1.setText("Agenter som ansvarar över flest aliens");

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel5.setText("Utcheckad utustning");

        jTree1.setBorder(null);
        jTree1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Lägg till:");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alien");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Utrustning");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ändra:");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alien");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Sök upp:");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alien per ras");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Registreringsdatum");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Plats");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Chef");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Information:");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alien");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setToolTipText("");
        jTree1.setRootVisible(false);
        jTree1.setShowsRootHandles(true);
        jTree1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTree1ComponentAdded(evt);
            }
        });
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        txtTopp1.setEditable(false);
        txtTopp1.setColumns(2);
        txtTopp1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        txtTopp1.setRows(3);
        txtTopp1.setTabSize(4);
        txtTopp1.setToolTipText("");
        txtTopp1.setAutoscrolls(false);
        txtTopp1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtTopp2.setEditable(false);
        txtTopp2.setColumns(2);
        txtTopp2.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        txtTopp2.setRows(3);
        txtTopp2.setTabSize(4);
        txtTopp2.setToolTipText("");
        txtTopp2.setAutoscrolls(false);
        txtTopp2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Svealand");

        jLabel3.setText("Götaland");

        jLabel4.setText("Norrland");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValkommen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNylosen)
                            .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTopp1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTopp2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTopp3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(264, 264, 264))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValkommen)
                    .addComponent(btnLoggaUt))
                .addGap(18, 18, 18)
                .addComponent(btnNylosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTopp3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTopp1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTopp2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toppListaSvealand() {

        ArrayList<HashMap<String, String>> topp;

        String fraga = "SELECT a.Namn , COUNT(Ansvarig_Agent) AS Antal FROM alien\n"
                + "JOIN agent a on a.Agent_ID = alien.Ansvarig_Agent\n"
                + "WHERE Omrade = 1\n"
                + "GROUP BY Ansvarig_Agent\n"
                + "ORDER BY COUNT(Ansvarig_Agent) DESC "
                + "LIMIT 3;";
        topp = SqlFragor.fragaRader(fraga);

        System.out.println(fraga);

        txtTopp1.append("Namn" + "   " + "Antal" + "\n");
        for (HashMap<String, String> t : topp) {
            txtTopp1.append(t.get("Namn") + "   " + t.get("Antal") + "\n");
        }
    }

    private void toppListaGotaland() {

        ArrayList<HashMap<String, String>> topp;

        String fraga = "SELECT a.Namn , COUNT(Ansvarig_Agent) AS Antal FROM alien\n"
                + "JOIN agent a on a.Agent_ID = alien.Ansvarig_Agent\n"
                + "WHERE Omrade = 2\n"
                + "GROUP BY Ansvarig_Agent\n"
                + "ORDER BY COUNT(Ansvarig_Agent) DESC "
                + "LIMIT 3;";
        topp = SqlFragor.fragaRader(fraga);

        System.out.println(fraga);

        txtTopp2.append("Namn" + "   " + "Antal" + "\n");
        for (HashMap<String, String> t : topp) {
            txtTopp2.append(t.get("Namn") + "   " + t.get("Antal") + "\n");
        }
    }

    private void toppListaNorrland() {

        ArrayList<HashMap<String, String>> topp;

        String fraga = "SELECT a.Namn , COUNT(Ansvarig_Agent) AS Antal FROM alien\n"
                + "JOIN agent a on a.Agent_ID = alien.Ansvarig_Agent\n"
                + "WHERE Omrade = 4\n"
                + "GROUP BY Ansvarig_Agent\n"
                + "ORDER BY COUNT(Ansvarig_Agent) DESC "
                + "LIMIT 3;";
        topp = SqlFragor.fragaRader(fraga);

        System.out.println(fraga);

        txtTopp3.append("Namn" + "   " + "Antal" + "\n");
        for (HashMap<String, String> t : topp) {
            txtTopp3.append(t.get("Namn") + "   " + t.get("Antal") + "\n");
        }
    }

    private void listaAllUtrustning() {

        ArrayList<HashMap<String, String>> allUtrustning;

        String id = SqlFragor.fragaSingel("SELECT Agent_id FROM agent WHERE Namn = '" + namn + "'");

        String utFraga = "SELECT Benamning FROM utrustning\n"
                + "join innehar_utrustning iu on utrustning.Utrustnings_ID = iu.Utrustnings_ID WHERE Agent_ID = " + id;
        allUtrustning = SqlFragor.fragaRader(utFraga);

        for (HashMap<String, String> utR : allUtrustning) {

            txtfUtrustning.append(utR.get("Benamning") + "\n");
        }
    }

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        new ForstaSida().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnNylosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNylosenActionPerformed
        new NyttLosen().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNylosenActionPerformed

    private void jTree1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTree1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1ComponentAdded

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked

        TreePath aa = jTree1.getSelectionPath();
        if (aa != null) {

            String bb = aa.toString();
            String string = bb.replaceAll("[\\[\\](){}]", "");
            String[] parts = string.split(",");

            if (parts.length > 2) {

                //                String part1 = parts[0]; // root
                String part2 = parts[1]; // parent
                String part3 = parts[2]; // leaf

                typ = part2.trim();
                fonster = part3.trim();

                if (typ.equals("Lägg till:")) {
                    switch (fonster) {
                        case "Alien":
                            new NyRegistreraAlien().setVisible(true);
                            dispose();
                            break;
                        case "Agent":
                            new AddAgent().setVisible(true);
                            dispose();
                            break;
                        case "Utrustning":
                            new AddUtrustning().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
                if (typ.equals("Ändra:")) {
                    switch (fonster) {
                        case "Alien":
                            new AndraAlien().setVisible(true);
                            dispose();
                            break;
                        case "Agent":
                            new AndraAgent().setVisible(true);
                            dispose();
                            break;
                        case "Chef":
                            new AndraChef().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
                if (typ.equals("Ta bort:")) {
                    switch (fonster) {
                        case "Alien":
                            new TaBortAlien().setVisible(true);
                            dispose();
                            break;
                        case "Agent":
                            new TaBortAgent().setVisible(true);
                            dispose();
                            break;
                        case "Utrustning":
                            new TaBortUtrustning().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
                if (typ.equals("Sök upp:")) {
                    switch (fonster) {
                        case "Alien per ras":
                            new AlienAvRas().setVisible(true);
                            dispose();
                            break;
                        case "Registreringsdatum":
                            new ValjAlienDatum().setVisible(true);
                            dispose();
                            break;
                        case "Plats":
                            new AllaAlienPlats().setVisible(true);
                            dispose();
                            break;
                        case "Chef":
                            new VemOmradesChef().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
                if (typ.equals("Information:")) {
                    switch (fonster) {
                        case "Alien":
                            new SokAllinfoAlien().setVisible(true);
                            dispose();
                            break;
                        case "Agent":
                            new AllInfoEnAgent().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
            }
        }
    }//GEN-LAST:event_jTree1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnNylosen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblValkommen;
    private javax.swing.JTextArea txtTopp1;
    private javax.swing.JTextArea txtTopp2;
    private javax.swing.JTextArea txtTopp3;
    private javax.swing.JTextArea txtfUtrustning;
    // End of variables declaration//GEN-END:variables
}
