/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test1;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.tree.TreePath;

/**
 *
 * @author nsags
 */
public class agentAdminSida extends javax.swing.JFrame {

    String namn;
    private String typ;
    private String fonster;

    /**
     * Creates new form agentAdminSida
     */
    public agentAdminSida() {
        initComponents();
        namn = forstaSida.aNamn();
        lblValkommen.setText("Välkommen " + namn);
        laggTillAtgard();
        listaAllUtrustning();
        for (int i = 0; i < jTree1.getRowCount(); i++) {
            jTree1.expandRow(i);
        }
    }

    private void laggTillAtgard() {

        cbKontrollAvAlien.addItem("Välj");
        cbKontrollAvAlien.addItem("Alla Alier per ras");
        cbKontrollAvAlien.addItem("Alla Alier per plats");
        cbKontrollAvAlien.addItem("Alla Alier per datum");
        cbKontrollAvAlien.addItem("Information om en alien");
        cbKontrollAvAlien.addItem("Ta bort alien");
        cbKontrollAvAlien.addItem("Ta bort agent");
        cbKontrollAvAlien.addItem("Ta bort utrustning");

        cbAtgarder.addItem("Välj");
        cbAtgarder.addItem("Lägg till Vapen");
        cbAtgarder.addItem("Lägg till Alien");
        cbAtgarder.addItem("Lägg till Agent");
        cbAtgarder.addItem("Ändra alien");
        cbAtgarder.addItem("Ändra agent");
        cbAtgarder.addItem("Ändra chef");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        cbKontrollAvAlien = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblValkommen = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();
        btnNylosen = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbAtgarder = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfUtrustning = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbKontrollAvAlien.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        cbKontrollAvAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKontrollAvAlienActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel2.setText("Kontroll av alien ");

        lblValkommen.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        lblValkommen.setText("jLabel1");

        btnLoggaUt.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        btnNylosen.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnNylosen.setText("Byt lösenord");
        btnNylosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNylosenActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel3.setText("Inloggad som administratör");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel4.setText("Åtgärder");

        cbAtgarder.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        cbAtgarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAtgarderActionPerformed(evt);
            }
        });

        txtfUtrustning.setEditable(false);
        txtfUtrustning.setColumns(1);
        txtfUtrustning.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        txtfUtrustning.setRows(5);
        jScrollPane1.setViewportView(txtfUtrustning);

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel5.setText("Utcheckad utustning");

        jTree1.setBorder(null);
        jTree1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Lägg till:");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alien");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Agent");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Utrustning");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ändra:");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alien");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Agent");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Chef");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ta bort:");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alien");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Agent");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Utrustning");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Sök upp:");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alien per ras");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Registreringsdatum");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Plats");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Information:");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Alien");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Agent");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setToolTipText("");
        jTree1.setRootVisible(false);
        jTree1.setShowsRootHandles(true);
        jTree1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTree1ComponentAdded(evt);
            }
        });
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValkommen)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbAtgarder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbKontrollAvAlien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(108, 108, 108)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(btnLoggaUt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNylosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnLoggaUt)
                        .addGap(18, 18, 18)
                        .addComponent(btnNylosen)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblValkommen)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cbAtgarder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbKontrollAvAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbKontrollAvAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKontrollAvAlienActionPerformed
        // Välj inloggningstyp
        int i = cbKontrollAvAlien.getSelectedIndex();

        if (i == 0) {

        }
        switch (i) {
            case 1:
                new alienAvRas().setVisible(true);
                dispose();
                break;
            case 2:
                new allaAlienPlats().setVisible(true);
                dispose();
                break;
            case 3:
                new alienDatum().setVisible(true);
                dispose();
                break;
            case 4:
                new sökAllinfoAlien().setVisible(true);
                dispose();
                break;
            case 5:
                new TaBortAlien().setVisible(true);
                dispose();
                break;
            case 6:
                new TaBortAgent().setVisible(true);
                dispose();
                break;
            case 7:
                new TaBortUtrustning().setVisible(true);
                dispose();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbKontrollAvAlienActionPerformed

    private void listaAllUtrustning() {

        String id = SqlFragor.fragaSingel("SELECT Agent_id FROM agent WHERE Namn = '" + namn + "';");
        String utFraga = "SELECT Benamning FROM utrustning join innehar_utrustning iu on utrustning.Utrustnings_ID = iu.Utrustnings_ID WHERE Agent_ID = " + id + ";";

        ArrayList<HashMap<String, String>> allUtrustning = SqlFragor.fragaRader(utFraga);

        for (HashMap<String, String> utR : allUtrustning) {
            txtfUtrustning.append(utR.get("Benamning") + "\n");
        }
    }

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        new forstaSida().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnNylosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNylosenActionPerformed
        new NyttLosen().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNylosenActionPerformed

    private void cbAtgarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAtgarderActionPerformed
        int i = cbAtgarder.getSelectedIndex();

        if (i == 0) {

        }
        switch (i) {
            case 1:
                new addUtrustning().setVisible(true);
                dispose();
                break;
            case 2:
                new nyRegistreraAlien().setVisible(true);
                dispose();
                break;
            case 3:
                new addAgent().setVisible(true);
                dispose();
                break;
            case 4:
                new AndraAlien().setVisible(true);
                dispose();
                break;
            case 5:
                new AndraAgent().setVisible(true);
                dispose();
                break;
            case 6:
                new AndraChef().setVisible(true);
                dispose();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbAtgarderActionPerformed

    private void jTree1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTree1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1ComponentAdded

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked

        TreePath aa = jTree1.getSelectionPath();
        if (aa != null) {

            String bb = aa.toString();
            String string = bb.replaceAll("[\\[\\](){}]", "");
            String[] parts = string.split(",");

            if (parts.length > 2) {

                //                String part1 = parts[0]; // root
                String part2 = parts[1]; // parent
                String part3 = parts[2]; // leaf

                typ = part2.trim();
                fonster = part3.trim();

                System.out.println(typ);
                System.out.println(fonster);

                if (typ.equals("Lägg till:")) {
                    switch (fonster) {
                        case "Alien":
                            new nyRegistreraAlien().setVisible(true);
                            dispose();
                            break;
                        case "Agent":
                            new addAgent().setVisible(true);
                            dispose();
                            break;
                        case "Utrustning":
                            new addUtrustning().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
                if (typ.equals("Ändra:")) {
                    switch (fonster) {
                        case "Alien":
                            new AndraAlien().setVisible(true);
                            dispose();
                            break;
                        case "Agent":
                            new AndraAgent().setVisible(true);
                            dispose();
                            break;
                        case "Chef":
                            new AndraChef().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
                if (typ.equals("Ta bort:")) {
                    switch (fonster) {
                        case "Alien":
                            new TaBortAlien().setVisible(true);
                            dispose();
                            break;
                        case "Agent":
                            new TaBortAgent().setVisible(true);
                            dispose();
                            break;
                        case "Utrustning":
                            new TaBortUtrustning().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
                if (typ.equals("Sök upp:")) {
                    switch (fonster) {
                        case "Alien per ras":
                            new alienAvRas().setVisible(true);
                            dispose();
                            break;
                        case "Registreringsdatum":
                            new alienDatum().setVisible(true);
                            dispose();
                            break;
                        case "Plats":
                            new allaAlienPlats().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
                if (typ.equals("Information:")) {
                    switch (fonster) {
                        case "Alien":
                            new sökAllinfoAlien().setVisible(true);
                            dispose();
                            break;
                        case "Agent":
                            new AllInfoEnAgent().setVisible(true);
                            dispose();
                            break;
                        default:
                            break;
                    }
                }
            }
        }
    }//GEN-LAST:event_jTree1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnNylosen;
    private javax.swing.JComboBox<String> cbAtgarder;
    private javax.swing.JComboBox<String> cbKontrollAvAlien;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblValkommen;
    private javax.swing.JTextArea txtfUtrustning;
    // End of variables declaration//GEN-END:variables
}
