/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test1;


import java.util.HashMap;


/**
 *
 * @author timme
 */
public class AllInfoEnAgent extends javax.swing.JFrame {

    /**
     *
     * Creates new form AllInfoEnAgent
     */
    public AllInfoEnAgent() {
        initComponents();
        Metoder.laggTillAgent(cbAnsvarigAgent);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBTillbaka = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextInfo2 = new javax.swing.JTextArea();
        cbAnsvarigAgent = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBTillbaka.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jBTillbaka.setText("Tillbaka");
        jBTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTillbakaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        jLabel2.setText("Info om Agent");

        jTextInfo2.setColumns(20);
        jTextInfo2.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jTextInfo2.setRows(5);
        jScrollPane1.setViewportView(jTextInfo2);

        cbAnsvarigAgent.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        cbAnsvarigAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj Agent" }));
        cbAnsvarigAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnsvarigAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBTillbaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(100, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(cbAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(cbAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(142, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTillbakaActionPerformed
        if (forstaSida.arAdmin()) {
            new agentAdminSida().setVisible(true);
            dispose();
        } else {
            new agentSida().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBTillbakaActionPerformed

    private void cbAnsvarigAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnsvarigAgentActionPerformed
         //HashMaplista som får en metod från SQLFragor-klassen.
        HashMap<String, String> info2;
        info2 = SqlFragor.fragaRad("SELECT * FROM agent WHERE NAMN = '" + cbAnsvarigAgent.getSelectedItem() + "'");
        
        
        String fraAgent = "SELECT Namn from agent JOIN omrade o on agent.Omrade = o.Omrades_ID WHERE Agent_ID = '"
                + cbAnsvarigAgent.getSelectedItem() + "' LIMIT 1";
        //Metod från SQLFragor-klassen.
        String agent = SqlFragor.fragaSingel(fraAgent);
        String fraOmrade = "SELECT Benamning FROM agent JOIN omrade o on agent.Omrade = o.Omrades_ID WHERE Agent_ID = "
                + info2.get("Omrade") + "  LIMIT 1";
        String omrade = SqlFragor.fragaSingel(fraOmrade);

        //Texten som skrivs ut är det som står innanför parameterna. "\n" skjuter ner texten efter en rad.
        jTextInfo2.setText("Namn: " + info2.get("Namn") + "\n" + "Telefon: " + info2.get("Telefon") + "\n" + "Anstallningsdatum: "
                + info2.get("Anstallningsdatum") + "\n" + "Administrator: " + info2.get("Administrator") + "\n" + "Losenord: "
                + info2.get("Losenord") + "\n" + "Område: " + omrade);
    }//GEN-LAST:event_cbAnsvarigAgentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAnsvarigAgent;
    private javax.swing.JButton jBTillbaka;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextInfo2;
    // End of variables declaration//GEN-END:variables
}
