/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test1;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author nsags
 */
public class NyttLosen extends javax.swing.JFrame {

    private String nuvarandeLosen;
    private String kontrollLosen;

    /**
     * Creates new form NyttLosen
     *
     */
    public NyttLosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstammer = new javax.swing.JLabel();
        rubrik = new javax.swing.JLabel();
        btnAvbryt = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNuvarandelosen = new javax.swing.JPasswordField();
        txtKontrollLosen = new javax.swing.JPasswordField();
        txtNyttLosen = new javax.swing.JPasswordField();
        cbVisaLosen = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstammer.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        rubrik.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        rubrik.setText("Byte av lösenord");

        btnAvbryt.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnAvbryt.setText("Tillbaka");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        btnOk.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel2.setText("Ange nuvarande lösenord");

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel3.setText("Ange nytt lösenord");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel4.setText("Ange nytt lösenord igen");

        txtNuvarandelosen.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        txtKontrollLosen.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        txtNyttLosen.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        txtNyttLosen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNyttLosenKeyPressed(evt);
            }
        });

        cbVisaLosen.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        cbVisaLosen.setText("Visa lösenord");
        cbVisaLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVisaLosenActionPerformed(evt);
            }
        });
        cbVisaLosen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbVisaLosenKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbVisaLosen)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(rubrik)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNuvarandelosen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKontrollLosen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNyttLosen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnOk))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lstammer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(46, 46, 46)
                        .addComponent(btnAvbryt)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(rubrik)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNuvarandelosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lstammer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKontrollLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvbryt)
                    .addComponent(btnOk)
                    .addComponent(txtNyttLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbVisaLosen)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        if (okUppgifter()) {
            if (ForstaSida.arManniska()) {
                nyttLosenAgent();
            } else {
                nyttLosenAlien();
            }
        }

//        if (ForstaSida.arManniska()) {
//            if (nuvarandeLosen.equals(kontrollLosen)) {
//                String nyttlosen = new String(ltxtNyttLosen.getPassword());
//                if (ForstaSida.aLosen().equals(nuvarandeLosen)) {
//                    SqlFragor.uppdatera("UPDATE agent SET Losenord = " + "'" + nyttlosen + "'" + " WHERE Namn = " + "'" + ForstaSida.aNamn() + "'");
//                    if (ForstaSida.arAdmin()) {
//                        dispose();
//                        new AgentAdminSida().setVisible(true);
//                        JOptionPane.showMessageDialog(null, "Lösenord har ändrats");
//                    } else {
//                        dispose();
//                        new AgentSida().setVisible(true);
//                        JOptionPane.showMessageDialog(null, "Lösenord har ändrats");
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(null, "Gamla lösenordet stämmer ej");
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "Det gamla lösenordet stämmer ej med varandra");
//            }
//        } else {
//            if (nuvarandeLosen.equals(kontrollLosen)) {
//                String nyttlosenAlien = new String(ltxtNyttLosen.getPassword());
//                if (ForstaSida.aLosen().equals(nuvarandeLosen)) {
//                    SqlFragor.uppdatera("UPDATE alien SET Losenord = " + "'" + nyttlosenAlien + "'" + " WHERE Namn = " + "'" + ForstaSida.aNamn() + "'");
//                } else {
//                    JOptionPane.showMessageDialog(null, "Gamla lösenordet stämmer ej");
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "Det gamla lösenordet stämmer ej med varandra");
//            }
//        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void nyttLosenAgent() {

        nuvarandeLosen = new String(txtNuvarandelosen.getPassword());
        String nyttLosen = new String(txtNyttLosen.getPassword());
        kontrollLosen = new String(txtKontrollLosen.getPassword());
        String reggatLosenAgent = SqlFragor.fragaSingel("SELECT Losenord FROM agent WHERE Namn = '" + ForstaSida.aNamn() + "';");

        if (nyttLosen.equals(kontrollLosen)) {
            if (reggatLosenAgent.equals(nuvarandeLosen)) {
                SqlFragor.uppdatera("UPDATE agent SET Losenord = " + "'" + nyttLosen + "'" + " WHERE Namn = " + "'" + ForstaSida.aNamn() + "'");
                if (ForstaSida.arAdmin()) {
                    dispose();
                    new AgentAdminSida().setVisible(true);
                    JOptionPane.showMessageDialog(null, "Lösenord har ändrats");
                } else {
                    dispose();
                    new AgentSida().setVisible(true);
                    JOptionPane.showMessageDialog(null, "Lösenord har ändrats");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Gamla lösenordet stämmer ej");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Det nya lösenordet stämmer ej med varandra");
        }
    }

    private void nyttLosenAlien() {

        nuvarandeLosen = new String(txtNuvarandelosen.getPassword());
        String nyttlosenAlien = new String(txtNyttLosen.getPassword());
        kontrollLosen = new String(txtKontrollLosen.getPassword());
        String reggatLosenAlien = SqlFragor.fragaSingel("SELECT Losenord FROM alien WHERE Namn = '" + ForstaSida.aNamn() + "';");

        if (nyttlosenAlien.equals(kontrollLosen)) {
            if (reggatLosenAlien.equals(nuvarandeLosen)) {
                SqlFragor.uppdatera("UPDATE alien SET Losenord = " + "'" + nyttlosenAlien + "'" + " WHERE Namn = " + "'" + ForstaSida.aNamn() + "'");
                dispose();
                new AlienSida().setVisible(true);
                JOptionPane.showMessageDialog(null, "Lösenord har ändrats");
            } else {
                JOptionPane.showMessageDialog(null, "Gamla lösenordet stämmer ej");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Det nya lösenordet stämmer ej med varandra");
        }
    }

    private boolean okUppgifter() {
        boolean ok = true;

        if (!ValideringsKlass.textFaltHarVarde(txtNuvarandelosen)) {
            ok = false;
            JOptionPane.showMessageDialog(null, "Ange nuvarande lösenord");
            txtNuvarandelosen.requestFocus();
        } else if (!ValideringsKlass.textFaltHarVarde(txtKontrollLosen)) {
            ok = false;
            JOptionPane.showMessageDialog(null, "Ange nytt lösenord");
            txtKontrollLosen.requestFocus();
        } else if (!ValideringsKlass.textFaltHarVarde(txtNyttLosen)) {
            ok = false;
            JOptionPane.showMessageDialog(null, "Ange nytt lösenord");
            txtNyttLosen.requestFocus();
        } else if (!ValideringsKlass.testLangdLosen(txtNyttLosen)) {
            ok = false;
            JOptionPane.showMessageDialog(null, "Lösenord får ej vara längre än sex tecken");
            txtKontrollLosen.requestFocus();
            txtKontrollLosen.selectAll();
        }
        return ok;
    }

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed

        if (ForstaSida.arManniska()) {
            if (ForstaSida.arAdmin()) {
                new AgentAdminSida().setVisible(true);
                dispose();
            } else {
                new AgentSida().setVisible(true);
                dispose();
            }
        } else {
            new AlienSida().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnAvbrytActionPerformed

    private void cbVisaLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVisaLosenActionPerformed
        if (cbVisaLosen.isSelected()) {
            txtNyttLosen.setEchoChar((char) 0);
        } else {
            txtNyttLosen.setEchoChar('*');
        }
    }//GEN-LAST:event_cbVisaLosenActionPerformed

    private void txtNyttLosenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNyttLosenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btnOk.doClick();
        }
    }//GEN-LAST:event_txtNyttLosenKeyPressed

    private void cbVisaLosenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbVisaLosenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btnOk.doClick();
        }
    }//GEN-LAST:event_cbVisaLosenKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox cbVisaLosen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lstammer;
    private javax.swing.JLabel rubrik;
    private javax.swing.JPasswordField txtKontrollLosen;
    private javax.swing.JPasswordField txtNuvarandelosen;
    private javax.swing.JPasswordField txtNyttLosen;
    // End of variables declaration//GEN-END:variables
}
