/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test1;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author nsags
 */
public class NyttLosen extends javax.swing.JFrame {

    private String nuvarandeLosen;
    private String kontrollLosen;

    /**
     * Creates new form NyttLosen
     *
     */
    public NyttLosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstammer = new javax.swing.JLabel();
        rubrik = new javax.swing.JLabel();
        btnAvbryt = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ltxtNuvarandelosen = new javax.swing.JPasswordField();
        ltxtKontrollLosen = new javax.swing.JPasswordField();
        ltxtNyttLosen = new javax.swing.JPasswordField();
        cbVisaLosen = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rubrik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rubrik.setText("Byte av lösenord");

        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel2.setText("Ange nuvarande lösenord");

        jLabel3.setText("Ange nuvarande lösenord igen");

        jLabel4.setText("Ange nytt lösenord");

        ltxtNuvarandelosen.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                ltxtNuvarandelosenCaretUpdate(evt);
            }
        });

        ltxtKontrollLosen.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                ltxtKontrollLosenCaretUpdate(evt);
            }
        });

        ltxtNyttLosen.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                ltxtNyttLosenCaretUpdate(evt);
            }
        });
        ltxtNyttLosen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ltxtNyttLosenKeyPressed(evt);
            }
        });

        cbVisaLosen.setText("Visa lösenord");
        cbVisaLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVisaLosenActionPerformed(evt);
            }
        });
        cbVisaLosen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbVisaLosenKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbVisaLosen)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(rubrik)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ltxtKontrollLosen)
                            .addComponent(ltxtNyttLosen, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnOk))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lstammer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(46, 46, 46)
                        .addComponent(btnAvbryt))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ltxtNuvarandelosen, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(rubrik)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ltxtNuvarandelosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lstammer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltxtKontrollLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvbryt)
                    .addComponent(btnOk)
                    .addComponent(ltxtNyttLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbVisaLosen)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        if (forstaSida.arManniska()) {
            if (nuvarandeLosen.equals(kontrollLosen)) {
                String nyttlosen = new String(ltxtNyttLosen.getPassword());
                if (forstaSida.aLosen().equals(nuvarandeLosen)) {
                    SqlFragor.uppdatera("UPDATE agent SET Losenord = " + "'" + nyttlosen + "'" + " WHERE Namn = " + "'" + forstaSida.aNamn() + "'");
                    if (forstaSida.arAdmin()) {
                        dispose();
                        new agentAdminSida().setVisible(true);
                        JOptionPane.showMessageDialog(null, "Lösenord har ändrats");
                    } else {
                        dispose();
                        new agentSida().setVisible(true);
                        JOptionPane.showMessageDialog(null, "Lösenord har ändrats");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Gamla lösenordet stämmer ej");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Det gamla lösenordet stämmer ej med varandra");
            }
        } else {
            if (nuvarandeLosen.equals(kontrollLosen)) {
                String nyttlosenAlien = new String(ltxtNyttLosen.getPassword());
                if (forstaSida.aLosen().equals(nuvarandeLosen)) {
                    SqlFragor.uppdatera("UPDATE alien SET Losenord = " + "'" + nyttlosenAlien + "'" + " WHERE Namn = " + "'" + forstaSida.aNamn() + "'");
                } else {
                    JOptionPane.showMessageDialog(null, "Gamla lösenordet stämmer ej");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Det gamla lösenordet stämmer ej med varandra");
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed

        if (forstaSida.arManniska()) {
            if (forstaSida.arAdmin()) {
                new agentAdminSida().setVisible(true);
                dispose();
            } else {
                new agentSida().setVisible(true);
                dispose();
            }
        } else {
            new alienSida().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnAvbrytActionPerformed

    private void cbVisaLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVisaLosenActionPerformed
        if (cbVisaLosen.isSelected()) {
            ltxtNyttLosen.setEchoChar((char) 0);
        } else {
            ltxtNyttLosen.setEchoChar('*');
        }
    }//GEN-LAST:event_cbVisaLosenActionPerformed

    private void ltxtNyttLosenCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_ltxtNyttLosenCaretUpdate
        nuvarandeLosen = new String(ltxtNuvarandelosen.getPassword());
    }//GEN-LAST:event_ltxtNyttLosenCaretUpdate

    private void ltxtKontrollLosenCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_ltxtKontrollLosenCaretUpdate
        kontrollLosen = new String(ltxtKontrollLosen.getPassword());

        if (nuvarandeLosen.equals(kontrollLosen)) {
            lstammer.setText("Stämmer");
        }
    }//GEN-LAST:event_ltxtKontrollLosenCaretUpdate

    private void ltxtNuvarandelosenCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_ltxtNuvarandelosenCaretUpdate
        nuvarandeLosen = new String(ltxtNuvarandelosen.getPassword());
    }//GEN-LAST:event_ltxtNuvarandelosenCaretUpdate

    private void ltxtNyttLosenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ltxtNyttLosenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btnOk.doClick();
        }
    }//GEN-LAST:event_ltxtNyttLosenKeyPressed

    private void cbVisaLosenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbVisaLosenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btnOk.doClick();
        }
    }//GEN-LAST:event_cbVisaLosenKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox cbVisaLosen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lstammer;
    private javax.swing.JPasswordField ltxtKontrollLosen;
    private javax.swing.JPasswordField ltxtNuvarandelosen;
    private javax.swing.JPasswordField ltxtNyttLosen;
    private javax.swing.JLabel rubrik;
    // End of variables declaration//GEN-END:variables
}
