/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test1;

import java.util.HashMap;


/**
 *
 * @author timme
 */
public class sökAllinfoAlien extends javax.swing.JFrame {

    /**
     * Creates new form sökAllinfoAlien
     */
    public sökAllinfoAlien() {
        initComponents();
        Metoder.laggTillAlien(cbAlien);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRubrik = new javax.swing.JLabel();
        jTextInfo = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();
        cbAlien = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRubrik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRubrik.setText("All info om Alien");

        jTextInfo.setColumns(2);
        jTextInfo.setRows(5);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        cbAlien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj Alien" }));
        cbAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 97, Short.MAX_VALUE)
                .addComponent(jRubrik)
                .addGap(146, 146, 146)
                .addComponent(btnTillbaka)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(cbAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTillbaka)
                    .addComponent(jRubrik))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTextInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(cbAlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        if (forstaSida.arAdmin()) {
            new agentAdminSida().setVisible(true);
            dispose();
        } else {
            new agentSida().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void cbAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlienActionPerformed
        String aNamn = cbAlien.getSelectedItem().toString();
        HashMap<String, String> info;
        info = SqlFragor.fragaRad("SELECT * FROM alien WHERE NAMN = '" + aNamn + "'");

        String fragaAnsvarig = "SELECT agent.Namn FROM alien join plats ON alien.Plats = plats.Plats_ID join agent On alien.Ansvarig_Agent = agent.Agent_ID WHERE Agent_ID = " + info.get("Ansvarig_Agent") + " LIMIT 1";
        String ansvarig = SqlFragor.fragaSingel(fragaAnsvarig);
        String fragaPlats = "SELECT Benamning FROM alien join plats ON alien.Plats = plats.Plats_ID join agent On alien.Ansvarig_Agent = agent.Agent_ID WHERE Agent_ID = " + info.get("Ansvarig_Agent") + " LIMIT 1";
        String plats = SqlFragor.fragaSingel(fragaPlats);

        jTextInfo.setText("Namn: " + info.get("Namn") + "\n" + "Registreringsdatum: " + info.get("Registreringsdatum") + "\n" + "Telefon: "
                + info.get("Telefon") + "\n" + "Plats: " + plats + "\n" + "Ansvarig agent: " + ansvarig);
    }//GEN-LAST:event_cbAlienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbAlien;
    private javax.swing.JLabel jRubrik;
    private javax.swing.JTextArea jTextInfo;
    // End of variables declaration//GEN-END:variables
}
