/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test1;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author timme
 */
public class TaBortAgent extends javax.swing.JFrame {

    /**
     * Creates new form TaBortAgent
     */
    public TaBortAgent() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        jLKorrekt = new javax.swing.JLabel();
        jAgent = new javax.swing.JLabel();
        jTAgent = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 20)); // NOI18N
        jLabel1.setText("Ta bort agent");

        btnTaBort.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnTillbaka.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        jAgent.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jAgent.setText("Agent:");

        jTAgent.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(btnTillbaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jAgent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTaBort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTAgent))
                        .addGap(55, 55, 55)
                        .addComponent(jLKorrekt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTillbaka))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLKorrekt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jAgent)
                        .addComponent(jTAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnTaBort)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        // TODO add your handling code here:
        
        //Det som skrivs in i jFramen "jTAgent" är den variabeln som vi använder i sql frågan för att specifera vilken alien som ska tas bort.
        String agentbort = jTAgent.getText();
        String taBortA = "SELECT Agent_ID FROM Agent WHERE Namn = '" + agentbort + "'";
        //Kallar på metoden från SQLFragor-klassen för att ta bort Agent_ID för den finns i flera tabeller (främmande nyckel).
        String idBortA = SqlFragor.fragaSingel(taBortA);
        String checking = "SELECT * FROM Agent WHERE Agent_ID = " + idBortA;

        //Checkar ifall värdet som skrivs in är null eller inte.
        if (SqlFragor.fragaSingel(checking) == null) {
            JOptionPane.showMessageDialog(rootPane, "Välj en agent!");
        } else {
            
            String tabortA = "DELETE FROM agent WHERE Agent_ID = " + idBortA;
            String tabortFA = "DELETE FROM faltagent WHERE Agent_ID = " + idBortA;
            String tabortIF = "DELETE FROM innehar_fordon WHERE Agent_ID = " + idBortA;
            String tabortIU = "DELETE FROM innehar_utrustning WHERE Agent_ID = " + idBortA;
            String tabortKC = "DELETE FROM kontorschef WHERE Agent_ID = " + idBortA;
            String tabortOC = "DELETE FROM omradeschef WHERE Agent_ID = " + idBortA;

            //Kallar på metoden från SQLFragor-klassen. Agent tas bort
            SqlFragor.taBort(tabortFA);
            SqlFragor.taBort(tabortIF);
            SqlFragor.taBort(tabortIU);
            SqlFragor.taBort(tabortKC);
            SqlFragor.taBort(tabortOC);
            SqlFragor.taBort(tabortA);

            jLKorrekt.setText(agentbort + " borttagen!");
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
        if (forstaSida.arAdmin()) {
            new agentAdminSida().setVisible(true);
            dispose();
        } else {
            new agentSida().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnTillbakaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jAgent;
    private javax.swing.JLabel jLKorrekt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTAgent;
    // End of variables declaration//GEN-END:variables
}
